CREATE TYPE e_country_status AS ENUM (
  'active', 
  'inactive' 
);

CREATE TABLE country (
  id              VARCHAR(2)        NOT NULL,
  name            TEXT              NOT NULL,
  alpha2_code     VARCHAR(2)        NOT NULL,
  alpha3_code     VARCHAR(3)        NOT NULL,
  numeric_code    VARCHAR(3)        NOT NULL,
  status          e_country_status  NOT NULL DEFAULT 'active',
	created_at      TIMESTAMP         NOT NULL DEFAULT now(),
	updated_at      TIMESTAMP         NULL,
	deleted_at      TIMESTAMP         NULL,
  CONSTRAINT country_pk PRIMARY KEY (id)

);

-- data
INSERT INTO country (id, name, alpha2_code, alpha3_code, numeric_code, status) VALUES
('AF',    'Afghanistan',                                  'AF',   	'AFG',	'004',    'active'),
('AL',    'Albania',                                      'AL',   	'ALB',	'008',    'active'),
('AQ',    'Antarctica',                                   'AQ',   	'ATA',	'010',    'active'),
('DZ',    'Algeria',                                      'DZ',   	'DZA',	'012',    'active'),
('AS',    'American Samoa',                               'AS',   	'ASM',	'016',    'active'),
('AD',    'Andorra',                                      'AD',   	'AND',	'020',    'active'),
('AO',    'Angola',                                       'AO',   	'AGO',	'024',    'active'),
('AG',    'Antigua and Barbuda',                          'AG',   	'ATG',	'028',    'active'),
('AZ',    'Azerbaijan',                                   'AZ',   	'AZE',	'031',    'active'),
('AR',    'Argentina',                                    'AR',   	'ARG',	'032',    'active'),
('AU',    'Australia',                                    'AU',   	'AUS',	'036',    'active'),
('AT',    'Austria',                                      'AT',   	'AUT',	'040',    'active'),
('BS',    'Bahamas',                                      'BS',   	'BHS',	'044',    'active'),
('BH',    'Bahrain',                                      'BH',   	'BHR',	'048',    'active'),
('BD',    'Bangladesh',                                   'BD',   	'BGD',	'050',    'active'),
('AM',    'Armenia',                                      'AM',   	'ARM',	'051',    'active'),
('BB',    'Barbados',                                     'BB',   	'BRB',	'052',    'active'),
('BE',    'Belgium',                                      'BE',   	'BEL',	'056',    'active'),
('BM',    'Bermuda',                                      'BM',   	'BMU',	'060',    'active'),
('BT',    'Bhutan',                                       'BT',   	'BTN',	'064',    'active'),
('BO',    'Bolivia',                                      'BO',   	'BOL',	'068',    'active'),
('BA',    'Bosnia and Herzegovina',                       'BA',   	'BIH',	'070',    'active'),
('BW',    'Botswana',                                     'BW',   	'BWA',	'072',    'active'),
('BV',    'Bouvet Island',                                'BV',   	'BVT',	'074',    'active'),
('BR',    'Brazil',                                       'BR',   	'BRA',	'076',    'active'),
('BZ',    'Belize',                                       'BZ',   	'BLZ',	'084',    'active'),
('IO',    'British Indian Ocean Territory',               'IO',   	'IOT',	'086',    'active'),
('SB',    'Solomon Islands',                              'SB',   	'SLB',	'090',    'active'),
('VG',    'British Virgin Islands',                       'VG',   	'VGB',	'092',    'active'),
('BN',    'Brunei Darussalam',                            'BN',   	'BRN',	'096',    'active'),
('BG',    'Bulgaria',                                     'BG',   	'BGR',	'100',    'active'),
('MM',    'Myanmar',                                      'MM',   	'MMR',	'104',    'active'),
('BI',    'Burundi',                                      'BI',   	'BDI',	'108',    'active'),
('BY',    'Belarus',                                      'BY',   	'BLR',	'112',    'active'),
('KH',    'Cambodia',                                     'KH',   	'KHM',	'116',    'active'),
('CM',    'Cameroon',                                     'CM',   	'CMR',	'120',    'active'),
('CA',    'Canada',                                       'CA',   	'CAN',	'124',    'active'),
('CV',    'Cape Verde',                                   'CV',   	'CPV',	'132',    'active'),
('KY',    'Cayman Islands',                               'KY',   	'CYM',	'136',    'active'),
('CF',    'Central African Republic',                     'CF',   	'CAF',	'140',    'active'),
('LK',    'Sri Lanka',                                    'LK',   	'LKA',	'144',    'active'),
('TD',    'Chad',                                         'TD',   	'TCD',	'148',    'active'),
('CL',    'Chile',                                        'CL',   	'CHL',	'152',    'active'),
('CN',    'China',                                        'CN',   	'CHN',	'156',    'active'),
('TW',    'Taiwan, Republic of China',                    'TW',   	'TWN',	'158',    'active'),
('CX',    'Christmas Island',                             'CX',   	'CXR',	'162',    'active'),
('CC',    'Cocos (Keeling) Islands',                      'CC',   	'CCK',	'166',    'active'),
('CO',    'Colombia',                                     'CO',   	'COL',	'170',    'active'),
('KM',    'Comoros',                                      'KM',   	'COM',	'174',    'active'),
('YT',    'Mayotte',                                      'YT',   	'MYT',	'175',    'active'),
('CG',    'Congo (Brazzaville)',                          'CG',   	'COG',	'178',    'active'),
('CD',    'Congo, (Kinshasa)',                            'CD',   	'COD',	'180',    'active'),
('CK',    'Cook Islands',                                 'CK',   	'COK',	'184',    'active'),
('CR',    'Costa Rica',                                   'CR',   	'CRI',	'188',    'active'),
('HR',    'Croatia',                                      'HR',   	'HRV',	'191',    'active'),
('CU',    'Cuba',                                         'CU',   	'CUB',	'192',    'active'),
('CY',    'Cyprus',                                       'CY',   	'CYP',	'196',    'active'),
('CZ',    'Czech Republic',                               'CZ',   	'CZE',	'203',    'active'),
('BJ',    'Benin',                                        'BJ',   	'BEN',	'204',    'active'),
('DK',    'Denmark',                                      'DK',   	'DNK',	'208',    'active'),
('DM',    'Dominica',                                     'DM',   	'DMA',	'212',    'active'),
('DO',    'Dominican Republic',                           'DO',   	'DOM',	'214',    'active'),
('EC',    'Ecuador',                                      'EC',   	'ECU',	'218',    'active'),
('SV',    'El Salvador',                                  'SV',   	'SLV',	'222',    'active'),
('GQ',    'Equatorial Guinea',                            'GQ',   	'GNQ',	'226',    'active'),
('ET',    'Ethiopia',                                     'ET',   	'ETH',	'231',    'active'),
('ER',    'Eritrea',                                      'ER',   	'ERI',	'232',    'active'),
('EE',    'Estonia',                                      'EE',   	'EST',	'233',    'active'),
('FO',    'Faroe Islands',                                'FO',   	'FRO',	'234',    'active'),
('FK',    'Falkland Islands (Malvinas)',                  'FK',   	'FLK',	'238',    'active'),
('GS',    'South Georgia and the South Sandwich Islands', 'GS',   	'SGS',	'239',    'active'),
('FJ',    'Fiji',                                         'FJ',   	'FJI',	'242',    'active'),
('FI',    'Finland',                                      'FI',   	'FIN',	'246',    'active'),
('AX',    'ALA	Aland Islands',                           'AX',  	'ALA',	'248',    'active'),
('FR',    'France',                                       'FR',   	'FRA',	'250',    'active'),
('GF',    'French Guiana',                                'GF',   	'GUF',	'254',    'active'),
('PF',    'French Polynesia',                             'PF',   	'PYF',	'258',    'active'),
('TF',    'French Southern Territories',                  'TF',   	'ATF',	'260',    'active'),
('DJ',    'Djibouti',                                     'DJ',   	'DJI',	'262',    'active'),
('GA',    'Gabon',                                        'GA',   	'GAB',	'266',    'active'),
('GE',    'Georgia',                                      'GE',   	'GEO',	'268',    'active'),
('GM',    'Gambia',                                       'GM',   	'GMB',	'270',    'active'),
('PS',    'Palestinian Territory',                        'PS',   	'PSE',	'275',    'active'),
('DE',    'Germany',                                      'DE',   	'DEU',	'276',    'active'),
('GH',    'Ghana',                                        'GH',   	'GHA',	'288',    'active'),
('GI',    'Gibraltar',                                    'GI',   	'GIB',	'292',    'active'),
('KI',    'Kiribati',                                     'KI',   	'KIR',	'296',    'active'),
('GR',    'Greece',                                       'GR',   	'GRC',	'300',    'active'),
('GL',    'Greenland',                                    'GL',   	'GRL',	'304',    'active'),
('GD',    'Grenada',                                      'GD',   	'GRD',	'308',    'active'),
('GP',    'Guadeloupe',                                   'GP',   	'GLP',	'312',    'active'),
('GU',    'Guam',                                         'GU',   	'GUM',	'316',    'active'),
('GT',    'Guatemala',                                    'GT',   	'GTM',	'320',    'active'),
('GN',    'Guinea',                                       'GN',   	'GIN',	'324',    'active'),
('GY',    'Guyana',                                       'GY',   	'GUY',	'328',    'active'),
('HT',    'Haiti',                                        'HT',   	'HTI',	'332',    'active'),
('HM',    'Heard and Mcdonald Islands',                   'HM',   	'HMD',	'334',    'active'),
('VA',    'Holy See (Vatican City State)',                'VA',   	'VAT',	'336',    'active'),
('HN',    'Honduras',                                     'HN',   	'HND',	'340',    'active'),
('HK',    'Hong Kong, SAR China',                         'HK',   	'HKG',	'344',    'active'),
('HU',    'Hungary',                                      'HU',   	'HUN',	'348',    'active'),
('IS',    'Iceland',                                      'IS',   	'ISL',	'352',    'active'),
('IN',    'India',                                        'IN',   	'IND',	'356',    'active'),
('ID',    'Indonesia',                                    'ID',   	'IDN',	'360',    'active'),
('IR',    'Iran, Islamic Republic of',                    'IR',   	'IRN',	'364',    'active'),
('IQ',    'Iraq',                                         'IQ',   	'IRQ',	'368',    'active'),
('IE',    'Ireland',                                      'IE',   	'IRL',	'372',    'active'),
('IL',    'Israel',                                       'IL',   	'ISR',	'376',    'active'),
('IT',    'Italy',                                        'IT',   	'ITA',	'380',    'active'),
('CI',    'Côte d''Ivoire',                                'CI',   	'CIV',	'384',    'active'),
('JM',    'Jamaica',                                      'JM',   	'JAM',	'388',    'active'),
('JP',    'Japan',                                        'JP',   	'JPN',	'392',    'active'),
('KZ',    'Kazakhstan',                                   'KZ',   	'KAZ',	'398',    'active'),
('JO',    'Jordan',                                       'JO',   	'JOR',	'400',    'active'),
('KE',    'Kenya',                                        'KE',   	'KEN',	'404',    'active'),
('KP',    'Korea (North)',                                'KP',   	'PRK',	'408',    'active'),
('KR',    'Korea (South)',                                'KR',   	'KOR',	'410',    'active'),
('KW',    'Kuwait',                                       'KW',   	'KWT',	'414',    'active'),
('KG',    'Kyrgyzstan',                                   'KG',   	'KGZ',	'417',    'active'),
('LA',    'Lao PDR',                                      'LA',   	'LAO',	'418',    'active'),
('LB',    'Lebanon',                                      'LB',   	'LBN',	'422',    'active'),
('LS',    'Lesotho',                                      'LS',   	'LSO',	'426',    'active'),
('LV',    'Latvia',                                       'LV',   	'LVA',	'428',    'active'),
('LR',    'Liberia',                                      'LR',   	'LBR',	'430',    'active'),
('LY',    'Libya',                                        'LY',   	'LBY',	'434',    'active'),
('LI',    'Liechtenstein',                                'LI',   	'LIE',	'438',    'active'),
('LT',    'Lithuania',                                    'LT',   	'LTU',	'440',    'active'),
('LU',    'Luxembourg',                                   'LU',   	'LUX',	'442',    'active'),
('MO',    'Macao, SAR China',                             'MO',   	'MAC',	'446',    'active'),
('MG',    'Madagascar',                                   'MG',   	'MDG',	'450',    'active'),
('MW',    'Malawi',                                       'MW',   	'MWI',	'454',    'active'),
('MY',    'Malaysia',                                     'MY',   	'MYS',	'458',    'active'),
('MV',    'Maldives',                                     'MV',   	'MDV',	'462',    'active'),
('ML',    'Mali',                                         'ML',   	'MLI',	'466',    'active'),
('MT',    'Malta',                                        'MT',   	'MLT',	'470',    'active'),
('MQ',    'Martinique',                                   'MQ',   	'MTQ',	'474',    'active'),
('MR',    'Mauritania',                                   'MR',   	'MRT',	'478',    'active'),
('MU',    'Mauritius',                                    'MU',   	'MUS',	'480',    'active'),
('MX',    'Mexico',                                       'MX',   	'MEX',	'484',    'active'),
('MC',    'Monaco',                                       'MC',   	'MCO',	'492',    'active'),
('MN',    'Mongolia',                                     'MN',   	'MNG',	'496',    'active'),
('MD',    'Moldova',                                      'MD',   	'MDA',	'498',    'active'),
('ME',    'Montenegro',                                   'ME',   	'MNE',	'499',    'active'),
('MS',    'Montserrat',                                   'MS',   	'MSR',	'500',    'active'),
('MA',    'Morocco',                                      'MA',   	'MAR',	'504',    'active'),
('MZ',    'Mozambique',                                   'MZ',   	'MOZ',	'508',    'active'),
('OM',    'Oman',                                         'OM',   	'OMN',	'512',    'active'),
('NA',    'Namibia',                                      'NA',   	'NAM',	'516',    'active'),
('NR',    'Nauru',                                        'NR',   	'NRU',	'520',    'active'),
('NP',    'Nepal',                                        'NP',   	'NPL',	'524',    'active'),
('NL',    'Netherlands',                                  'NL',   	'NLD',	'528',    'active'),
('AN',    'Netherlands Antilles',                         'AN',   	'ANT',	'530',    'active'),
('AW',    'Aruba',                                        'AW',   	'ABW',	'533',    'active'),
('NC',    'New Caledonia',                                'NC',   	'NCL',	'540',    'active'),
('VU',    'Vanuatu',                                      'VU',   	'VUT',	'548',    'active'),
('NZ',    'New Zealand',                                  'NZ',   	'NZL',	'554',    'active'),
('NI',    'Nicaragua',                                    'NI',   	'NIC',	'558',    'active'),
('NE',    'Niger',                                        'NE',   	'NER',	'562',    'active'),
('NG',    'Nigeria',                                      'NG',   	'NGA',	'566',    'active'),
('NU',    'Niue',                                         'NU',   	'NIU',	'570',    'active'),
('NF',    'Norfolk Island',                               'NF',   	'NFK',	'574',    'active'),
('NO',    'Norway',                                       'NO',   	'NOR',	'578',    'active'),
('MP',    'Northern Mariana Islands',                     'MP',   	'MNP',	'580',    'active'),
('UM',    'US Minor Outlying Islands',                    'UM',   	'UMI',	'581',    'active'),
('FM',    'Micronesia, Federated States of',              'FM',   	'FSM',	'583',    'active'),
('MH',    'Marshall Islands',                             'MH',   	'MHL',	'584',    'active'),
('PW',    'Palau',                                        'PW',   	'PLW',	'585',    'active'),
('PK',    'Pakistan',                                     'PK',   	'PAK',	'586',    'active'),
('PA',    'Panama',                                       'PA',   	'PAN',	'591',    'active'),
('PG',    'Papua New Guinea',                             'PG',   	'PNG',	'598',    'active'),
('PY',    'Paraguay',                                     'PY',   	'PRY',	'600',    'active'),
('PE',    'Peru',                                         'PE',   	'PER',	'604',    'active'),
('PH',    'Philippines',                                  'PH',   	'PHL',	'608',    'active'),
('PN',    'Pitcairn',                                     'PN',   	'PCN',	'612',    'active'),
('PL',    'Poland',                                       'PL',   	'POL',	'616',    'active'),
('PT',    'Portugal',                                     'PT',   	'PRT',	'620',    'active'),
('GW',    'Guinea-Bissau',                                'GW',   	'GNB',	'624',    'active'),
('TL',    'Timor-Leste',                                  'TL',   	'TLS',	'626',    'active'),
('PR',    'Puerto Rico',                                  'PR',   	'PRI',	'630',    'active'),
('QA',    'Qatar',                                        'QA',   	'QAT',	'634',    'active'),
('RE',    'Réunion',                                      'RE',   	'REU',	'638',    'active'),
('RO',    'Romania',                                      'RO',   	'ROU',	'642',    'active'),
('RU',    'Russian Federation',                           'RU',   	'RUS',	'643',    'active'),
('RW',    'Rwanda',                                       'RW',   	'RWA',	'646',    'active'),
('BL',    'Saint-Barthélemy',                             'BL',   	'BLM',	'652',    'active'),
('SH',    'Saint Helena',                                 'SH',   	'SHN',	'654',    'active'),
('KN',    'Saint Kitts and Nevis',                        'KN',   	'KNA',	'659',    'active'),
('AI',    'Anguilla',                                     'AI',   	'AIA',	'660',    'active'),
('LC',    'Saint Lucia',                                  'LC',   	'LCA',	'662',    'active'),
('MF',    'Saint-Martin (French part)',                   'MF',   	'MAF',	'663',    'active'),
('PM',    'Saint Pierre and Miquelon',                    'PM',   	'SPM',	'666',    'active'),
('VC',    'Saint Vincent and Grenadines',                 'VC',   	'VCT',	'670',    'active'),
('SM',    'San Marino',                                   'SM',   	'SMR',	'674',    'active'),
('ST',    'Sao Tome and Principe',                        'ST',   	'STP',	'678',    'active'),
('SA',    'Saudi Arabia',                                 'SA',   	'SAU',	'682',    'active'),
('SN',    'Senegal',                                      'SN',   	'SEN',	'686',    'active'),
('RS',    'Serbia',                                       'RS',   	'SRB',	'688',    'active'),
('SC',    'Seychelles',                                   'SC',   	'SYC',	'690',    'active'),
('SL',    'Sierra Leone',                                 'SL',   	'SLE',	'694',    'active'),
('SG',    'Singapore',                                    'SG',   	'SGP',	'702',    'active'),
('SK',    'Slovakia',                                     'SK',   	'SVK',	'703',    'active'),
('VN',    'Viet Nam',                                     'VN',   	'VNM',	'704',    'active'),
('SI',    'Slovenia',                                     'SI',   	'SVN',	'705',    'active'),
('SO',    'Somalia',                                      'SO',   	'SOM',	'706',    'active'),
('ZA',    'South Africa',                                 'ZA',   	'ZAF',	'710',    'active'),
('ZW',    'Zimbabwe',                                     'ZW',   	'ZWE',	'716',    'active'),
('ES',    'Spain',                                        'ES',   	'ESP',	'724',    'active'),
('SS',    'South Sudan',                                  'SS',   	'SSD',	'728',    'active'),
('EH',    'Western Sahara',                               'EH',   	'ESH',	'732',    'active'),
('SD',    'Sudan',                                        'SD',   	'SDN',	'736',    'active'),
('SR',    'Suriname',                                     'SR',   	'SUR',	'740',    'active'),
('SJ',    'Svalbard and Jan Mayen Islands',               'SJ',   	'SJM',	'744',    'active'),
('SZ',    'Swaziland',                                    'SZ',   	'SWZ',	'748',    'active'),
('SE',    'Sweden',                                       'SE',   	'SWE',	'752',    'active'),
('CH',    'Switzerland',                                  'CH',   	'CHE',	'756',    'active'),
('SY',    'Syrian Arab Republic (Syria)',                 'SY',   	'SYR',	'760',    'active'),
('TJ',    'Tajikistan',                                   'TJ',   	'TJK',	'762',    'active'),
('TH',    'Thailand',                                     'TH',   	'THA',	'764',    'active'),
('TG',    'Togo',                                         'TG',   	'TGO',	'768',    'active'),
('TK',    'Tokelau',                                      'TK',   	'TKL',	'772',    'active'),
('TO',    'Tonga',                                        'TO',   	'TON',	'776',    'active'),
('TT',    'Trinidad and Tobago',                          'TT',   	'TTO',	'780',    'active'),
('AE',    'United Arab Emirates',                         'AE',   	'ARE',	'784',    'active'),
('TN',    'Tunisia',                                      'TN',   	'TUN',	'788',    'active'),
('TR',    'Turkey',                                       'TR',   	'TUR',	'792',    'active'),
('TM',    'Turkmenistan',                                 'TM',   	'TKM',	'795',    'active'),
('TC',    'Turks and Caicos Islands',                     'TC',   	'TCA',	'796',    'active'),
('TV',    'Tuvalu',                                       'TV',   	'TUV',	'798',    'active'),
('UG',    'Uganda',                                       'UG',   	'UGA',	'800',    'active'),
('UA',    'Ukraine',                                      'UA',   	'UKR',	'804',    'active'),
('MK',    'Macedonia, Republic of',                       'MK',   	'MKD',	'807',    'active'),
('EG',    'Egypt',                                        'EG',   	'EGY',	'818',    'active'),
('GB',    'United Kingdom',                               'GB',   	'GBR',	'826',    'active'),
('GG',    'Guernsey',                                     'GG',   	'GGY',	'831',    'active'),
('JE',    'Jersey',                                       'JE',   	'JEY',	'832',    'active'),
('IM',    'Isle of Man',                                  'IM',   	'IMN',	'833',    'active'),
('TZ',    'Tanzania, United Republic of',                 'TZ',   	'TZA',	'834',    'active'),
('US',    'United States of America',                     'US',   	'USA',	'840',    'active'),
('VI',    'Virgin Islands, US',                           'VI',   	'VIR',	'850',    'active'),
('BF',    'Burkina Faso',                                 'BF',   	'BFA',	'854',    'active'),
('UY',    'Uruguay',                                      'UY',   	'URY',	'858',    'active'),
('UZ',    'Uzbekistan',                                   'UZ',   	'UZB',	'860',    'active'),
('VE',    'Venezuela (Bolivarian Republic)',              'VE',   	'VEN',	'862',    'active'),
('WF',    'Wallis and Futuna Islands',                    'WF',   	'WLF',	'876',    'active'),
('WS',    'Samoa',                                        'WS',   	'WSM',	'882',    'active'),
('YE',    'Yemen',                                        'YE',   	'YEM',	'887',    'active'),
('ZM',    'Zambia',                                       'ZM',   	'ZMB',	'894',    'active');

